<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="antenna" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.1" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="axel_offset" value="0.05" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find antenna_description)/urdf/antenna.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find antenna_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
	<box size="0.72 0.72 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <geometry>
	<box size="0.72 0.72 0.1"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1" ixy="0.0" ixz="0.0"
	  iyy="1" iyz="0.0"
	  izz="1"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 0.5" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.8"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.8"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0.4" rpy="0 0 0"/>
      <mass value="4.69"/>
      <inertia
	  ixx="0.25" ixy="0.0" ixz="0.0"
	  iyy="0.25" iyz="0.0"
	  izz="0.006"/>
    </inertial>
  </link>

  <joint name="joint2" type="revolute">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 0 0.45" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="30" lower="-1.571" upper="1.571" velocity="1.571"/>
    <dynamics damping="0.7"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.8 0.2"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.8 0.2"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <mass value="1.56"/>
      <inertia
	  ixx="0.0884" ixy="0.0" ixz="0.0"
	  iyy="0.0065" iyz="0.0"
	  izz="0.0845"/>
    </inertial>
  </link>

  <joint name="joint3" type="fixed">
    <!-- <axis xyz="0 1 0" /> -->
    <!-- <origin xyz="0 0 ${height3 - axel_offset/2}" rpy="0 0 0"/> -->
    <parent link="link3"/>
    <child link="link4"/>
  </joint>

  <link name="link4">
    <collision>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.6"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.1" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.05" radius="0.6"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <mass value="4" />
      <origin xyz="0 0 0.025" rpy="0 0 0"/>
      <inertia ixx="0.00083" ixy="0" ixz="0" iyy="0.00083" iyz="0" izz="0.00083" />
    </inertial>
  </link>

  <joint name="joint4" type="fixed">
    <!-- <axis xyz="0 1 0" /> -->
    <!-- <origin xyz="${camera_link} 0 ${height3 - axel_offset*2}" rpy="0 0 0"/> -->
    <parent link="link4"/>
    <child link="link5"/>
  </joint>

  <!-- Camera -->
  <link name="link5">
    <collision>
      <origin xyz="0 0 0.25" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.5" radius="0.03"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0.25" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.5" radius="0.03"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <mass value="0.05" />
      <origin xyz="0 0 0.25" rpy="0 0 0"/>
      <inertia ixx="0.004" ixy="0" ixz="0" iyy="0.004" iyz="0" izz="0.004" />
    </inertial>
  </link>

  <!-- generate an optical frame http://www.ros.org/reps/rep-0103.html#suffix-frames
      so that ros and opencv can operate on the camera frame correctly -->

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

</robot>
