antenna:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  leg_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg_joint
    pid: {p: 3.0, i: 0.01, d: 0.1}
  dish_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: dish_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}